[[services]]
name = "indexer"
dockerfile = "Dockerfile"

# Отдельный сервис для первого запуска
[[services]]
name = "volume-init"
dockerfile = "Dockerfile.cron"

[[services]]
name = "volume-cron"
dockerfile = "Dockerfile.cron"

[services.volume-cron]
cron = "0 * * * *"